# 
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
#  
# <https://github.com/KFERMercer/OpenWrt-CI>
#


name: Merge-upstream

on:
  release:
    types: published
  push:
#    branches:
#      - master
    paths:
      - '.github/workflows/merge-upstream.yml'
  
  schedule:
    - cron: 30 19 * * *
  # push:
  #   branches: 
  #     - master 

jobs:

  merge:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "ycg31@qq.com"
        git config --global user.name "ycg31"

    - name: Load upstream commits
      run: |
        git checkout -b Ameykyl-master master
        git pull https://github.com/Ameykyl/openwrt18.06.git master

    - name: Push Commits
      run: |
        git checkout master
        git merge --no-ff Ameykyl-master
        git push origin master
